import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container max-w-4xl mx-auto px-4 py-16">
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>
        
        <h1 className="text-4xl font-bold mb-4">Terms of Use for Dream Metrics</h1>
        <p className="text-muted-foreground mb-8">Last updated: December 16, 2025</p>
        
        <div className="space-y-8 text-muted-foreground">
          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using the Dream Metrics mobile application ("App"), 
              you agree to be bound by these Terms of Use ("Terms"). If you do not agree to these Terms, 
              please do not use the App.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">2. Description of Service</h2>
            <p>
              Dream Metrics is a mobile application that allows users to record their dreams and receive 
              AI-generated interpretations. The interpretations are provided for entertainment and 
              self-reflection purposes only and should not be considered professional psychological, 
              medical, or therapeutic advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">3. User Accounts</h2>
            <p className="mb-4">
              To use certain features of the App, you must sign in using Apple Sign-In. You are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-3">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use of your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">4. In-App Purchases</h2>
            <p className="mb-4">
              The App offers in-app purchases ("Credits") that allow you to access dream interpretation features:
            </p>
            <ul className="list-disc pl-6 space-y-3">
              <li>All purchases are processed through Apple's App Store and are subject to Apple's terms and conditions</li>
              <li>Credits are non-transferable and cannot be exchanged for cash</li>
              <li>Unused credits remain in your account until used or until account deletion</li>
              <li>Refunds are handled according to Apple's refund policy</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">5. User Content</h2>
            <p className="mb-4">
              You retain ownership of the dream descriptions you submit ("User Content"). By submitting User Content, you grant us a limited license to:
            </p>
            <ul className="list-disc pl-6 space-y-3">
              <li>Process and store your dreams for the purpose of providing interpretations</li>
              <li>Use anonymized, aggregated data to improve our services</li>
            </ul>
            <p className="mt-4">
              You agree not to submit content that is illegal, harmful, threatening, abusive, or otherwise objectionable.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">6. Intellectual Property</h2>
            <p>
              The App, including its design, features, and content (excluding User Content), is owned by 
              Dream Metrics and is protected by intellectual property laws. You may not copy, modify, 
              distribute, or reverse engineer any part of the App without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">7. Disclaimer of Warranties</h2>
            <p>
              THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, 
              EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, 
              ERROR-FREE, OR SECURE. DREAM INTERPRETATIONS ARE GENERATED BY AI AND ARE FOR 
              ENTERTAINMENT PURPOSES ONLY. WE MAKE NO CLAIMS REGARDING THE ACCURACY, RELIABILITY, 
              OR COMPLETENESS OF ANY INTERPRETATION.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, DREAM METRICS SHALL NOT BE LIABLE FOR ANY 
              INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF 
              PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, 
              USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE APP.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Dream Metrics and its officers, directors, 
              employees, and agents from any claims, damages, losses, liabilities, and expenses 
              (including attorney's fees) arising out of your use of the App or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the App at any time, 
              with or without cause, and with or without notice. Upon termination, your right 
              to use the App will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">11. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. We will notify you of material changes by 
              posting the updated Terms within the App. Your continued use of the App after 
              changes are posted constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable laws, 
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">13. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at:{" "}
              <a 
                href="mailto:dreammetrics@proton.me" 
                className="text-primary hover:text-accent transition-colors underline underline-offset-4"
              >
                dreammetrics@proton.me
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
